### PR TITLE
[FLOC-1537] New Homebrew recipe

### PR DESCRIPTION
**Pull request by adamtheturtle**
Test with:

```
export VERSION=0.3.3dev8
brew update
brew install --verbose --debug https://raw.githubusercontent.com/ClusterHQ/homebrew-tap/release/flocker-${VERSION}/flocker-${VERSION}.rb
brew test flocker-${VERSION}
```

### CODE REVIEW

**Comment by exarkun** [comment]
The author metadata on the commit is wrong.  This has happened before as well.  It's not the most important thing in the world but I think you actually should fix your development environment so it stops happening (and then optionally fix this commit).

**Comment by adamtheturtle** [comment]
This is not an issue with my development environment but an issue with the release process. An issue to fix this is at https://clusterhq.atlassian.net/browse/FLOC-1561.

**Comment by adamtheturtle** [comment]
This is a problem with the release process separate to the times it has happened before because the release process requires a *new* Vagrant dev machine to be set up.

**Comment by exarkun** [comment]
Manual testing suggests this works.  Please merge.

**Pull request merged**
